CONTIKI_SOURCEFILES += cxmac.c xmac.c nullmac.c lpp.c frame802154.c sicslowmac.c nullrdc.c nullrdc-noframer.c mac.c 
CONTIKI_SOURCEFILES += framer-nullmac.c framer-802154.c csma.c contikimac.c phase.c
CONTIKI_SOURCEFILES += credential.c
CONTIKI_SOURCEFILES += akm-authentication.c akm-break-security-association.c akm-mac.c akm-beacon.c akm-insert-node.c akm-temporary-link.c
CONTIKI_SOURCEFILES += akm-cycle-detect.c
CONTIKI_SOURCEFILES += assert.c
